version: "2"
services:
    mariadb:
        container_name: mariadb
        image: mariadb:10.4.12
        volumes:
        - /home/vagrant/mariadb:/var/lib/mysql:rw
        - /home/vagrant/mariadb-backups:/var/lib/mysql-backups:rw
        ports:
        - "9082:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Root
        restart: always
