version: "2"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.12
    volumes:
    - /home/vagrant/mariadb:/var/lib/mysql:rw
    - /home/vagrant/mariadb-backups:/var/lib/mysql-backups:rw
    ports:
    - "9082:3306"
    environment:
        MYSQL_ROOT_PASSWORD: Root
    restart: unless-stopped
  trustydaemon:
    image: shukriadams/trusty-daemon:latest
    container_name: trustydaemon
    # duplicity needs hostname to be constant
    hostname : trustydaemon 
    restart: unless-stopped
    ports:
    - "3100:3000"
    volumes:
      - ./settings.yml:/var/app/settings.yml
      - ./jobs:/var/app/jobs:rw
      - ./logs:/var/app/logs:rw
      - /home/vagrant/mariadb-backups:/var/lib/mysql-backups
      # this exposes all docker containers to trusty-daemon
      - "/var/run/docker.sock:/var/run/docker.sock"
      