version: "2"
services:
  postgres:
    image: shukriadams/postgres-plus:9.6
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passwurd
      PGDATA: /var/lib/postgresql/data/mydata # needed to allow postgress to mount to external volume folder
    ports:
    - "5432:5432"
    - "3100:3000"
    volumes:
      - ./data:/var/lib/postgresql/data/mydata:rw
      - ./backups:/var/app/backups:rw
      - ./settings.yml:/var/app/settings.yml
    # Caveat : this command MUST be disabled when initializing the container. Initializing will create and set the 
    # rights for the data volume mount, and is managed internally by the container. Once initialized, re-enable
    # command to start both the backup server and postgres service
    command: su postgres -c "cd /var/app && pm2 start app.js --name "postgres-backup" && /usr/lib/postgresql/9.6/bin/postgres"

      