version: "2"
services:
  trustydaemon:
    image: shukriadams/trusty-daemon:latest
    container_name: trustydaemon
    restart: unless-stopped
    ports:
    - "3100:3000"
    volumes:
      - ./settings.yml:/var/app/settings.yml
      - ./operationLogs:/var/app/operationLogs:rw
      - ./logs:/var/app/logs:rw
    command: sh -c "cd /var/app && node index"
      