version: "2"
services:
  postgres:
    image: shukriadams/postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passwurd
      PGDATA: /var/lib/postgresql/data/mydata # needed to allow postgress to mount to external volume folder
    ports:
    - "5432:5432"
    - "3100:3000"
    command: /bin/sh -c "while true ;sleep 5; do continue; done"
    volumes:
      - ./data:/var/lib/postgresql/data/mydata:rw
      - ./backups:/var/app/backups:rw

