FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install nodejs -y \
    && apt-get install npm -y \
    && apt-get install docker -y \
    && mkdir -p /var/app 

# copy the build zip in, unpack, strips the first two folders when unzipping, getting rid of /tmp/build
# then clean up build.zip
COPY ./build.tar.gz /tmp
RUN tar -xzvf /tmp/build.tar.gz -C /var/app --strip 2
RUN rm /tmp/build.tar.gz

# cd to app and start, do not use WORKDIR, as this makes it complicated to change start CMD 
# and debug later
CMD cd /var/app && npm start