version: 1
port: 3000
onstart: apt-get install duplicity -y && apt-get install python-boto -y && apt-get install lftp -y
jobs:
    jenkins:
        cronmask: "*/10 * * * * *"
        command: "export PASSPHRASE=whatever \
                 && export FTP_PASSWORD=myftppassword \
                 && duplicity --exclude '/foo/bar/exclude/**/stuff/**' /foo/bar ftp://myuser@myServer/foo"
        logResults: true
        enabled: false
